### ISSUE TITLE
css conflict in document preview

### ISSUE THREAD

**Issue by YJack0000** [YJack0000/document-center-fe#15]
![Screenshot 2024-06-04 at 3 39 02 PM](https://github.com/YJack0000/document-center-fe/assets/49984479/339f2010-af2c-4877-b639-444b8d6e3056)

**Comment by YJack0000** [comment]
Also, please make some public document that have codes and photos include.

**Comment by yui0303** [comment]
> ![Screenshot 2024-06-04 at 3 39 02 PM](https://github.com/YJack0000/document-center-fe/assets/49984479/339f2010-af2c-4877-b639-444b8d6e3056)
> 
> 

How do you route to the page. Because there is no conflict for me.

**Comment by YJack0000** [comment]
Do you using dark mode in your macbook?

**Comment by yui0303** [comment]
Oh, I see. I manage to disable it.
