### ISSUE TITLE
Action not passing even with the most basic testing, please check

### ISSUE THREAD

**Issue by YJack0000** [YJack0000/document-center-fe#9]
https://github.com/YJack0000/document-center-fe/actions/runs/9338902729

**Comment by yui0303** [comment]
It's wired! The test is pass in local PC.

**Comment by YJack0000** [comment]
https://stackoverflow.com/questions/75895415/cypress-test-cases-in-github-actions-with-local-server-localhost3000-the-tes

How about this?

**Comment by yui0303** [comment]
@YJack0000 See #10.
